name: Build and deploy Angular app to Azure Web App - reservasahfrontend

on:
  push:
    branches:
      - azure-branch-ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod

      - name: Zip artifact for deployment
        run: |
          cd dist/sistema_reservas_frontend
          zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: angular-app
          path: dist/sistema_reservas_frontend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: angular-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d dist/sistema_reservas_frontend

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'reservasahfrontend'
          slot-name: 'Production'
          package: dist/sistema_reservas_frontend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
